name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_WORKFLOW }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name kbresume16121981 --auth-mode key -d '$web' -s --overwrite true .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "KBresumeWeb" --name "kbresumeweb" --resource-group "ResumeKB"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
